quarkus:
  application:
    name: rest-heroes
  log:
    level: INFO
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      level: INFO
      darken: 1
  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    cors: true
    port: 8083
    test-port: 0
  jackson:
    serialization-inclusion: non-empty
  smallrye-openapi:
    info-title: Hero API
    info-description: This API allows CRUD operations on a hero
    info-version: 1.0
    info-contact-name: Quarkus
    info-contact-url: https://github.com/quarkusio
    servers: "http://localhost:${quarkus.http.port}"
  swagger-ui:
    always-include: true
  container-image:
    builder: docker
    registry: quay.io
    group: quarkus-super-heroes
    name: "${quarkus.application.name}"
  kubernetes:
    part-of: heroes-service
    annotations:
      "app.openshift.io/connects-to": heroes-db
    env:
      configmaps: "${quarkus.application.name}-config"
      secrets: "${quarkus.application.name}-config-creds"
    labels:
      app: "${quarkus.application.name}"
      application: "${quarkus.kubernetes.part-of}"
      system: quarkus-super-heroes
  openshift:
    part-of: "${quarkus.kubernetes.part-of}"
    route:
      expose: true
    annotations:
      "app.openshift.io/connects-to": heroes-db
    env:
      configmaps: "${quarkus.kubernetes.env.configmaps}"
      secrets: "${quarkus.kubernetes.env.secrets}"
    labels:
      app: "${quarkus.kubernetes.labels.app}"
      application: "${quarkus.openshift.part-of}"
      system: "${quarkus.kubernetes.labels.system}"
  knative:
    part-of: "${quarkus.kubernetes.part-of}"
    annotations:
      "app.openshift.io/connects-to": heroes-db
    env:
      configmaps: "${quarkus.kubernetes.env.configmaps}"
      secrets: "${quarkus.kubernetes.env.secrets}"
    labels:
      app: "${quarkus.kubernetes.labels.app}"
      application: "${quarkus.openshift.part-of}"
      system: "${quarkus.kubernetes.labels.system}"

"%prod":
  quarkus:
    hibernate-orm:
      sql-load-script: import.sql
