
  event-statistics-native-java11:
    image: quay.io/quarkus-super-heroes/event-statistics:native-java11-latest-rhbq-2.7
    container_name: event-statistics-native-java11
    depends_on:
      - apicurio
      - fights-kafka
    ports:
      - "8085:8085"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
    restart: on-failure
    networks:
      default:
        aliases:
          - event-statistics
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
