---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    name: prometheus
    system: quarkus-super-heroes
spec:
  ports:
    - port: 9090
      name: scrape
      protocol: TCP
      targetPort: 9090
  selector:
    name: prometheus
  type: ClusterIP
